import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthenticatorWrapper from "./AuthenticatorWrapper";
import "@aws-amplify/ui-react/styles.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" data-bs-theme="dark">
      <body>
        <nav className="bg-gray-900 text-white">
          <div className="mx-auto max-w-7xl px-4">
            <div className="flex h-16 items-center justify-between">
              <div className="text-lg font-bold">
                テーマパーク
              </div>
            </div>
          </div>
        </nav>
      
        <AuthenticatorWrapper>
          <div className="mx-auto max-w-7xl px-4 py-6">
            {children}
          </div>
        </AuthenticatorWrapper>
      </body>
    </html>
  );
}
